import { CustomerProfile } from "./types";

interface ProfileBase {
  avatar: string;
  name: string;
  age: string;
  occupation: string;
  goals: string[];
  painPoints: string[];
  contentWants: string;
  followReason: string;
  engagementScore: "High" | "Medium" | "Low";
  purchasePotential: "High" | "Medium" | "Low";
  preferredFormats: ("Reels" | "Photos" | "Carousels" | "Mixed")[];
  hashtags?: string[];
}

// ─── Profile Database ──────────────────────────────────────────────────────────

const PROFILES: Record<string, ProfileBase[]> = {
  "Fitness & Wellness": [
    {
      avatar: "💼",
      name: "Sarah",
      age: "27–34",
      occupation: "Marketing Manager",
      goals: ["Lose weight without giving up her social life", "Build a 30-minute daily workout habit", "Reduce stress through movement"],
      painPoints: ["No time for long gym sessions", "Tried 5 diets that none stuck", "Feels overwhelmed by contradictory advice online"],
      contentWants: "Quick, realistic workouts and nutrition tips that fit a busy 9-to-5 schedule",
      followReason: "You post content she can actually do — no 5am ice baths, no unrealistic body standards",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
      hashtags: ["fitnessmotivation", "workoutathome", "busygirlwellness"],
    },
    {
      avatar: "🎓",
      name: "Jake",
      age: "19–25",
      occupation: "College Student",
      goals: ["Build muscle on a tight budget", "Learn to train without a trainer", "Look better and feel more confident"],
      painPoints: ["Can't afford a gym membership or supplements", "Doesn't know where to start", "Intimidated by experienced gym-goers"],
      contentWants: "Budget-friendly workouts, form tutorials, and beginner-safe advice",
      followReason: "You explain the basics without making him feel stupid for not knowing them",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
      hashtags: ["collegefit", "budgetgym", "beginnerfitness"],
    },
    {
      avatar: "👩‍👧",
      name: "Maria",
      age: "30–42",
      occupation: "Stay-at-Home Parent",
      goals: ["Reclaim her pre-baby body and energy", "Workout at home with no equipment", "Set a healthy example for her kids"],
      painPoints: ["Nap windows are the only free time she has", "Lost confidence after pregnancy", "Gym feels like another chore to manage"],
      contentWants: "20-minute home workouts and real talk about body changes after kids",
      followReason: "You're honest about the messy middle — not just the after photos",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
      hashtags: ["momfitness", "postpartumfitness", "homeworkoutmom"],
    },
    {
      avatar: "🏃",
      name: "David",
      age: "35–50",
      occupation: "Sales Executive",
      goals: ["Maintain fitness while traveling for work", "Fix chronic lower back pain", "Hit a new PR in his next half marathon"],
      painPoints: ["Hotel gyms are useless", "Injuries keep derailing his training", "Doesn't have time to research the right programs"],
      contentWants: "Travel-friendly workouts, injury prevention, and data-driven training tips",
      followReason: "You give specific, evidence-backed advice — not generic motivation",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
      hashtags: ["runningcommunity", "travelworkout", "athletelife"],
    },
    {
      avatar: "✨",
      name: "Priya",
      age: "24–32",
      occupation: "Nurse",
      goals: ["Decompress after exhausting 12-hour shifts", "Build sustainable healthy habits", "Avoid the weight gain that comes with shift work"],
      painPoints: ["Irregular schedule wrecks her routines", "Eats hospital cafeteria food constantly", "Too tired to cook or work out after night shifts"],
      contentWants: "Simple recovery routines, meal prep ideas, and grace-based wellness content",
      followReason: "You don't shame people for being tired — you meet them where they are",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Carousels"],
      hashtags: ["nurselife", "shiftworkhealth", "selfcarenurse"],
    },
  ],

  "Food & Cooking": [
    {
      avatar: "🏙️",
      name: "Alex",
      age: "24–35",
      occupation: "Software Engineer",
      goals: ["Stop ordering takeout every night", "Meal prep efficiently for the week", "Actually enjoy cooking instead of dreading it"],
      painPoints: ["Only knows how to make pasta and scrambled eggs", "Buys ingredients and lets them rot", "Recipes online always assume too much skill"],
      contentWants: "Foolproof beginner recipes with simple ingredients and no fancy equipment",
      followReason: "You make cooking feel achievable for someone who genuinely can't cook",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
    },
    {
      avatar: "💪",
      name: "Danielle",
      age: "26–38",
      occupation: "Personal Trainer",
      goals: ["Fuel her workouts with the right macros", "Find high-protein meals that don't taste like cardboard", "Teach clients about nutrition alongside fitness"],
      painPoints: ["Tired of chicken, rice, and broccoli every day", "High-protein recipes are usually expensive", "Clients ask her nutrition questions she can't fully answer"],
      contentWants: "High-protein, macro-friendly recipes that are actually delicious",
      followReason: "You prove that healthy food doesn't have to be boring or expensive",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "👨‍👩‍👧",
      name: "Tom",
      age: "32–45",
      occupation: "Dad / Project Manager",
      goals: ["Cook real dinners for his family in under 30 minutes", "Stop relying on frozen meals", "Impress his partner with one new dish a week"],
      painPoints: ["Gets home at 6:30pm with hungry kids", "Doesn't know what to do with half the ingredients", "Always forgets to defrost the meat"],
      contentWants: "Fast family meals with ingredients he can find at any supermarket",
      followReason: "You speak his language — fast, practical, zero pretension",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "🌿",
      name: "Mia",
      age: "22–30",
      occupation: "Graduate Student",
      goals: ["Eat well on a $50/week grocery budget", "Cook plant-based meals she actually enjoys", "Develop a signature dinner party dish"],
      painPoints: ["Vegan recipes are often complicated or expensive", "Lives in a tiny kitchen with minimal equipment", "Gets bored eating the same 5 meals"],
      contentWants: "Budget vegan/veggie cooking with big flavors and simple techniques",
      followReason: "You show that eating well on a budget is possible and genuinely tasty",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Carousels"],
    },
    {
      avatar: "🍷",
      name: "Rachel",
      age: "35–50",
      occupation: "Interior Designer",
      goals: ["Level up her dinner party hosting", "Learn professional cooking techniques at home", "Build a repertoire of 10 showstopper dishes"],
      painPoints: ["Intermediate recipes are hard to find — too basic or too advanced", "Doesn't know how to pair food with wine", "Presentation always looks amateur"],
      contentWants: "Restaurant-quality techniques simplified for home cooks who want to impress",
      followReason: "You bridge the gap between beginner and professional in a way no cooking show does",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
  ],

  "Travel": [
    {
      avatar: "💼",
      name: "Chris",
      age: "26–38",
      occupation: "Consultant",
      goals: ["See 10 new countries in the next 3 years", "Travel smarter and cheaper using points", "Combine work trips with real travel"],
      painPoints: ["Doesn't know how to use credit card points effectively", "Work schedule makes long trips impossible", "Worried about safety in unfamiliar places"],
      contentWants: "Efficient travel hacks, points strategies, and weekend trip itineraries",
      followReason: "You show how to travel smart without quitting your job",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🌸",
      name: "Emma",
      age: "23–32",
      occupation: "Teacher",
      goals: ["Travel solo safely as a woman", "See Southeast Asia on a teacher's salary", "Find authentic experiences off the tourist trail"],
      painPoints: ["Safety concerns as a solo female traveler", "Tourism feels fake and overcrowded", "Budget travel content often skips the important details"],
      contentWants: "Honest solo female travel guides with safety tips and real budget breakdowns",
      followReason: "You make solo travel feel safe, achievable, and not lonely",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "👨‍👩‍👦",
      name: "The Hendersons",
      age: "32–45",
      occupation: "Parents (Various)",
      goals: ["Take a family vacation that everyone actually enjoys", "Travel without spending $10k", "Create memories without the stress"],
      painPoints: ["Kids ruin spontaneous travel — everything needs planning", "Travel content is either solo or couples — nothing for families", "Worried about flights with toddlers"],
      contentWants: "Family-friendly destinations, packing tips with kids, and realistic travel expectations",
      followReason: "You show what travel actually looks like with kids — chaos and magic included",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "🎒",
      name: "Leo",
      age: "20–28",
      occupation: "Freelancer / Digital Nomad",
      goals: ["Work remotely from 5 countries this year", "Find the best Wi-Fi cafes and co-working spots", "Live abroad for under $1,500/month"],
      painPoints: ["Visa rules are confusing and keep changing", "Loneliness is real but nobody talks about it", "Finding stable Wi-Fi while traveling is harder than it sounds"],
      contentWants: "Digital nomad city guides, visa tips, and honest nomad lifestyle content",
      followReason: "You're honest about the hard parts — not just the Instagram highlights",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "💍",
      name: "Sophie",
      age: "27–36",
      occupation: "HR Manager",
      goals: ["Plan the perfect honeymoon", "Experience luxury travel without luxury prices", "Discover hidden romantic destinations"],
      painPoints: ["Honeymoon packages are overpriced and generic", "Hard to find honest reviews of 'romantic' hotels", "Doesn't know how to upgrade travel experience on a mid-range budget"],
      contentWants: "Romantic travel destinations, luxury-for-less tips, and couple travel guides",
      followReason: "You help her feel like she can have the dream trip without the dream budget",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Photos", "Carousels"],
    },
  ],

  "Fashion": [
    {
      avatar: "👔",
      name: "James",
      age: "24–35",
      occupation: "Account Manager",
      goals: ["Build a wardrobe that works for office and weekends", "Stop panic-buying before events", "Develop his own style instead of copying others"],
      painPoints: ["Has no idea what 'smart casual' actually means", "Spends money on clothes he never wears", "Fashion content is always aimed at women"],
      contentWants: "Men's style basics, capsule wardrobe guides, and dressing for different occasions",
      followReason: "You make fashion accessible for men who actually want to try but don't know how",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "✨",
      name: "Zoe",
      age: "22–32",
      occupation: "Social Media Coordinator",
      goals: ["Find her signature style", "Shop sustainably without sacrificing style", "Build a versatile wardrobe on a grad salary"],
      painPoints: ["Sustainable fashion is usually expensive and boring", "Impulse buys don't work with anything she owns", "Trends change too fast to keep up"],
      contentWants: "Outfit formulas, thrift hauls, and style tips that don't require a designer budget",
      followReason: "You help her look put-together without spending or overconsumming",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "👗",
      name: "Linda",
      age: "40–55",
      occupation: "Office Manager",
      goals: ["Dress stylishly at 45+ without looking like she's trying too hard", "Update her wardrobe without spending a fortune", "Feel confident getting dressed every morning"],
      painPoints: ["Fashion content is aimed at 20-somethings", "Doesn't know what's age-appropriate vs age-limiting", "Her old style feels outdated but she doesn't know how to evolve it"],
      contentWants: "Age-inclusive style tips and how to dress your best at every decade",
      followReason: "You show that great style has no age limit and never makes her feel invisible",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Photos"],
    },
    {
      avatar: "🌟",
      name: "Ava",
      age: "18–26",
      occupation: "University Student",
      goals: ["Look good on a shoestring budget", "Master thrift shopping and upcycling", "Stand out with her own aesthetic"],
      painPoints: ["Everything trendy is too expensive", "Thrift shopping feels random and hit-or-miss", "Trends she loves don't suit her body type"],
      contentWants: "Budget fashion hacks, thrift tips, and styling advice for different body types",
      followReason: "You make fashion creative and fun rather than aspirational and unattainable",
      engagementScore: "High",
      purchasePotential: "Low",
      preferredFormats: ["Reels", "Mixed"],
    },
  ],

  "Beauty & Skincare": [
    {
      avatar: "🔬",
      name: "Natasha",
      age: "25–38",
      occupation: "Pharmacist",
      goals: ["Build a science-backed skincare routine", "Fix hyperpigmentation without harsh treatments", "Stop wasting money on products that don't work"],
      painPoints: ["Skincare marketing is full of pseudoscience and empty claims", "Spent hundreds on products with no results", "Can't tell which ingredients actually do what"],
      contentWants: "Ingredient breakdowns, evidence-based skincare, and honest product reviews",
      followReason: "You cut through the marketing and give her the science she can trust",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🌙",
      name: "Aisha",
      age: "20–30",
      occupation: "Receptionist",
      goals: ["Achieve clear skin on a drugstore budget", "Find makeup that actually works for her skin tone", "Build a simple routine she'll actually stick to"],
      painPoints: ["Most beauty content doesn't cater to darker skin tones", "Can't afford Sephora prices", "Gets overwhelmed by 10-step routines"],
      contentWants: "Budget-friendly beauty for all skin tones with minimal steps and maximum results",
      followReason: "You finally represent her skin tone and don't assume she has a $200 budget",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "👩‍💼",
      name: "Claire",
      age: "30–45",
      occupation: "Lawyer",
      goals: ["Slow down the signs of aging with the right actives", "Find a morning routine under 10 minutes", "Invest in products that are actually worth the price"],
      painPoints: ["Anti-aging marketing is fear-based and overwhelming", "No time for elaborate routines", "Doesn't know the difference between retinol, retinal, and tretinoin"],
      contentWants: "Honest anti-aging content with product comparisons and realistic expectations",
      followReason: "You explain the science without the fear-mongering and respect her intelligence",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "🌿",
      name: "Lily",
      age: "22–32",
      occupation: "Yoga Instructor",
      goals: ["Transition fully to clean beauty and skincare", "Find products that are ethical and sustainable", "Understand what 'clean' actually means vs greenwashing"],
      painPoints: ["Clean beauty brands are expensive and inconsistent", "Can't tell greenwashing from genuine sustainability", "Natural alternatives don't always work as well as the real thing"],
      contentWants: "Honest clean beauty reviews that call out greenwashing and celebrate what works",
      followReason: "You research so she doesn't have to — and you're honest when natural options fall short",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
  ],

  "Tech & Gadgets": [
    {
      avatar: "🚀",
      name: "Marcus",
      age: "25–40",
      occupation: "Product Manager",
      goals: ["Stay ahead of AI tools that affect his industry", "Build a productivity setup that maximizes deep work", "Cut unnecessary software costs"],
      painPoints: ["Can't keep up with the pace of new AI tools", "Pays for 12 subscriptions he barely uses", "Too many productivity systems, not enough actual productivity"],
      contentWants: "Practical AI tool reviews, productivity stack recommendations, and ROI-focused tech advice",
      followReason: "You save him hours of research and only recommend things that actually earn their price",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🎮",
      name: "Tyler",
      age: "18–28",
      occupation: "Customer Service Rep",
      goals: ["Build a solid PC/gaming setup on a budget", "Learn to use tech to start earning money online", "Stay on top of the latest releases"],
      painPoints: ["Tech content is either too beginner or too advanced", "Budget builds are hard to find with real comparisons", "Gets confused by spec sheets and marketing jargon"],
      contentWants: "Budget tech reviews, beginner explanations without condescension, and value-for-money comparisons",
      followReason: "You help him make smart buying decisions without needing a CS degree to understand them",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "👩‍💻",
      name: "Priya",
      age: "28–42",
      occupation: "Small Business Owner",
      goals: ["Use AI to automate repetitive tasks in her business", "Protect her business from cyber threats", "Find affordable tech that replaces expensive software"],
      painPoints: ["Overwhelmed by tech decisions and doesn't know who to trust", "Worried about data privacy for her clients", "Has wasted money on software that didn't fit her workflow"],
      contentWants: "Small business tech guides, AI tools for non-technical people, and cybersecurity basics",
      followReason: "You explain tech in business terms — ROI, time saved, risk reduced — not features",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "📱",
      name: "Ryan",
      age: "30–50",
      occupation: "Teacher",
      goals: ["Understand the tech his students use before they do", "Use AI tools to plan lessons faster", "Protect his family's digital privacy"],
      painPoints: ["Always feels one step behind when it comes to tech", "Most tech content assumes more knowledge than he has", "Worried about screen time and data collection on his kids' devices"],
      contentWants: "Approachable tech content for non-techies with real practical applications",
      followReason: "You make him feel smart rather than stupid about tech — and you actually explain the 'why'",
      engagementScore: "Medium",
      purchasePotential: "Medium",
      preferredFormats: ["Carousels", "Reels"],
    },
  ],

  "Business & Entrepreneurship": [
    {
      avatar: "🔥",
      name: "Jordan",
      age: "23–33",
      occupation: "9-to-5 Employee",
      goals: ["Replace his salary with a side business in 18 months", "Validate a business idea without quitting his job", "Build a personal brand that opens doors"],
      painPoints: ["Doesn't know which business idea is worth pursuing", "Scared of failure and judgment from people he knows", "Information overload — too many gurus, conflicting advice"],
      contentWants: "Real, actionable steps to start and validate a business while working full-time",
      followReason: "You went through the same thing and you show the messy middle — not just the success",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "💻",
      name: "Sam",
      age: "26–38",
      occupation: "Freelancer",
      goals: ["Scale from solo freelancing to an agency or productized service", "Raise rates without losing clients", "Build passive income alongside client work"],
      painPoints: ["Income is feast or famine with no predictability", "Doesn't know how to charge what he's worth", "Working 60 hours a week but not growing"],
      contentWants: "Pricing strategy, client acquisition, and scaling advice for established freelancers",
      followReason: "You speak to where he actually is — not beginners or unicorn-round startups",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "🌟",
      name: "Keisha",
      age: "30–45",
      occupation: "Solopreneur / Coach",
      goals: ["Build a course or digital product that sells while she sleeps", "Grow her email list to 5,000 subscribers", "Establish herself as an authority in her niche"],
      painPoints: ["Launches fall flat despite huge effort", "Doesn't understand copywriting or marketing psychology", "Gives away too much for free without converting to paid"],
      contentWants: "Marketing, launch strategy, and audience-building content for service-based businesses",
      followReason: "You understand the coaching/creator business model and give advice that's actually relevant to her",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🏪",
      name: "Raj",
      age: "35–52",
      occupation: "Local Business Owner",
      goals: ["Bring his offline business online and reach new customers", "Understand digital marketing without hiring an agency", "Use Instagram and content to drive real sales"],
      painPoints: ["Paid thousands to an agency with zero results", "Doesn't understand what content to post or why", "His business is doing okay locally but he feels capped"],
      contentWants: "Digital marketing fundamentals and Instagram strategy built specifically for local/product businesses",
      followReason: "You make digital marketing feel applicable to a real-world business, not just online entrepreneurs",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
  ],

  "Photography & Videography": [
    {
      avatar: "📸",
      name: "Caleb",
      age: "20–30",
      occupation: "University Student",
      goals: ["Turn his photography hobby into paid work", "Build a portfolio that attracts clients", "Learn to shoot and edit at a professional level"],
      painPoints: ["Doesn't know how to find his first paying client", "Auto mode is holding him back but manual feels overwhelming", "Gear feels expensive and he doesn't know where to invest first"],
      contentWants: "Beginner-to-intermediate photography tutorials and the business side of becoming a photographer",
      followReason: "You document your journey in a way that makes him believe he can do it too",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Carousels"],
    },
    {
      avatar: "💑",
      name: "Jess",
      age: "26–38",
      occupation: "Wedding Photographer",
      goals: ["Raise her pricing to $3k+ per wedding", "Attract clients who value her style and trust her creative vision", "Streamline her editing workflow to save 5 hours per wedding"],
      painPoints: ["Clients keep negotiating her prices down", "Spends 30+ hours editing a single wedding", "Her portfolio doesn't communicate the premium she wants to charge"],
      contentWants: "Posing, editing workflow, pricing strategy, and brand positioning for wedding photographers",
      followReason: "You speak directly to the business reality of professional photography — not just the art",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "🎬",
      name: "Noah",
      age: "22–32",
      occupation: "Content Creator / YouTuber",
      goals: ["Upgrade his video quality without upgrading his whole setup", "Learn cinematic techniques on a mirrorless camera", "Build a filmmaking aesthetic that's recognizable"],
      painPoints: ["His footage looks flat and amateur no matter what he tries", "Color grading takes him hours and never looks right", "YouTube tutorials are scattered and often outdated"],
      contentWants: "Cinematic filmmaking tutorials, camera settings deep-dives, and workflow optimization",
      followReason: "You teach techniques that immediately improve his videos — not theory, visible results",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Mixed"],
    },
  ],

  "Education & Learning": [
    {
      avatar: "📚",
      name: "Kevin",
      age: "18–26",
      occupation: "University Student",
      goals: ["Improve his grades without studying more hours", "Develop habits that actually stick", "Figure out what he wants to do with his life"],
      painPoints: ["Studies hard but retains almost nothing", "Starts habit systems and abandons them within two weeks", "Anxious about the future and comparing himself to peers"],
      contentWants: "Study techniques, habit science, and career clarity content aimed at students",
      followReason: "You give him real tools and also acknowledge that this phase of life is genuinely hard",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🌱",
      name: "Monica",
      age: "28–42",
      occupation: "Career Changer",
      goals: ["Teach herself a new skill and transition industries", "Make the most of commute and lunch break time for learning", "Build credibility in a field she's new to"],
      painPoints: ["Doesn't know if her self-taught skills are good enough", "Can't afford to go back to school full-time", "Imposter syndrome is constant and crippling"],
      contentWants: "Self-education roadmaps, certification advice, and encouragement for adult learners",
      followReason: "You validate the non-traditional path and give her a concrete map forward",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "👨‍🏫",
      name: "Daniel",
      age: "30–50",
      occupation: "Teacher / Trainer",
      goals: ["Make his lessons more engaging and memorable", "Learn how to teach online and reach more students", "Stay ahead of how AI is changing education"],
      painPoints: ["Students are disengaged and he doesn't know why", "Wants to create online content but doesn't know where to start", "Feels like the education system is changing faster than he can adapt"],
      contentWants: "Teaching strategies, online course creation, and education technology guidance",
      followReason: "You help him be a better educator, not just survive the classroom",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
  ],

  "Lifestyle": [
    {
      avatar: "⚡",
      name: "Olivia",
      age: "24–35",
      occupation: "Graphic Designer",
      goals: ["Build a morning routine she actually loves", "Create a life that feels intentional, not reactive", "Find balance between productivity and rest"],
      painPoints: ["Hits snooze 4 times and starts every day reactive", "Social media comparison leaves her feeling inadequate", "Every self-improvement trend exhausts her before she even tries it"],
      contentWants: "Gentle, realistic lifestyle content that doesn't make her feel like she's failing",
      followReason: "You make intentional living feel calm and achievable — not another thing to optimize",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "🧘",
      name: "Ben",
      age: "28–40",
      occupation: "Burnout Recovering Professional",
      goals: ["Rebuild structure after burnout", "Find meaning beyond career achievement", "Build habits that are sustainable not punishing"],
      painPoints: ["Every productivity system feels like more pressure", "Doesn't know who he is outside of work", "Relapsed into old patterns after every attempt at change"],
      contentWants: "Recovery from burnout, identity beyond work, and low-pressure lifestyle redesign",
      followReason: "You speak to the person who has tried everything and is exhausted — and you don't judge",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🏡",
      name: "Anna",
      age: "30–45",
      occupation: "Working Parent",
      goals: ["Feel less overwhelmed by the daily juggle", "Create family rituals that everyone looks forward to", "Find 30 minutes a day that's actually hers"],
      painPoints: ["Guilt about not doing enough at work or at home — always both", "No time or energy for herself by the end of the day", "Lifestyle content feels like it assumes she's childless and has 3 free hours"],
      contentWants: "Real, messy, honest lifestyle content for people with actual responsibilities",
      followReason: "You don't pretend life is easier than it is — and you still find beauty in it",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
    },
  ],

  "Comedy & Entertainment": [
    {
      avatar: "😂",
      name: "Tyler",
      age: "18–28",
      occupation: "Retail Worker",
      goals: ["Get genuine laughs, not just polite ones", "Build a loyal audience for his humor", "Eventually make money doing something he loves"],
      painPoints: ["His friends laugh but strangers scroll past", "Doesn't know how to structure comedy for short video", "Compares himself to big creators and feels hopeless"],
      contentWants: "Comedy mechanics, what makes people share a video, and how to find his comedic voice",
      followReason: "You're genuinely funny AND you explain why you're funny — rare combination",
      engagementScore: "High",
      purchasePotential: "Low",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "🎭",
      name: "Jada",
      age: "22–35",
      occupation: "Aspiring Creator",
      goals: ["Build an audience around her specific humor and personality", "Figure out which platform fits her best", "Create without burning out or losing her authentic voice"],
      painPoints: ["Feels like all the good comedy niches are taken", "Gets in her own head and second-guesses everything before posting", "Doesn't know when a video is ready or good enough"],
      contentWants: "Creator mindset content, finding your comedic niche, and the business side of entertainment",
      followReason: "You prove that specific humor builds stronger communities than broad appeal",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
  ],

  "Finance & Investing": [
    {
      avatar: "💸",
      name: "Maya",
      age: "24–35",
      occupation: "Nurse",
      goals: ["Pay off $40k in student loans in 5 years", "Start investing with whatever's left", "Stop feeling anxious every time she checks her bank account"],
      painPoints: ["Makes decent money but has nothing to show for it", "Finance content is too complex or too dumbed-down", "Too scared to invest because she's afraid of losing money"],
      contentWants: "Honest personal finance for people with real debt and real salaries — not theoretical wealth-building",
      followReason: "You talk about money like a real person and don't make her feel judged for her starting point",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "📈",
      name: "Ethan",
      age: "28–40",
      occupation: "Mid-Career Professional",
      goals: ["Build a real investment portfolio — not just a savings account", "Understand whether his current financial decisions are smart", "Achieve financial independence before 50"],
      painPoints: ["Has a 401k but has no idea if it's actually optimized", "Gets overwhelmed by investment options and freezes", "Financial advisors always try to sell him something"],
      contentWants: "Investment strategy, tax optimization, and financial independence planning for mid-income earners",
      followReason: "You give real advice without trying to sell him anything — that's genuinely rare",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
    {
      avatar: "🎓",
      name: "Arjun",
      age: "21–28",
      occupation: "Recent Graduate",
      goals: ["Start building wealth from his first real paycheck", "Understand investing before it's too late to start early", "Avoid the money mistakes his parents made"],
      painPoints: ["Doesn't know where to even begin with investing", "Social pressure to spend on lifestyle before saving", "Finance feels like a different language"],
      contentWants: "Beginner investing guides, money basics, and wealth-building habits for young adults",
      followReason: "You make him feel like starting late is still starting — and that every dollar matters",
      engagementScore: "High",
      purchasePotential: "Low",
      preferredFormats: ["Reels", "Carousels"],
    },
  ],

  "Pets & Animals": [
    {
      avatar: "🐕",
      name: "Hannah",
      age: "25–38",
      occupation: "Office Worker",
      goals: ["Solve her dog's reactivity issues on leash", "Build a deeper bond through training", "Stop feeling embarrassed at the dog park"],
      painPoints: ["Her dog embarrasses her every time they go outside", "Trainers are expensive and she can't afford weekly sessions", "YouTube tutorials contradict each other constantly"],
      contentWants: "Step-by-step positive reinforcement training guides she can do at home",
      followReason: "You explain the WHY behind training techniques — it actually changes how she thinks about her dog",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
    },
    {
      avatar: "🐱",
      name: "Sophia",
      age: "22–35",
      occupation: "Graphic Designer (WFH)",
      goals: ["Understand what her cat is actually communicating", "Keep her indoor cat mentally stimulated", "Find vet-approved nutrition advice she can trust"],
      painPoints: ["Cat randomly attacks her and she doesn't know why", "Her cat seems bored and she doesn't know how to help", "Vet bills shock her every time something comes up"],
      contentWants: "Cat behavior explained, enrichment ideas, and health content she can act on without a vet visit",
      followReason: "You translate cat behavior in a way that makes her feel like she finally speaks the language",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "🐾",
      name: "Mike",
      age: "30–50",
      occupation: "Dad",
      goals: ["Find the right dog for his family with young kids", "Keep the family pet healthy on a mid-range budget", "Teach his kids how to respect and care for animals"],
      painPoints: ["Doesn't know which breed suits a family environment", "Vet bills are unpredictable and stressful", "His kids are rough with the dog and he doesn't know how to manage it"],
      contentWants: "Family-friendly pet content: breed guides, budget pet care tips, and kid-dog safety",
      followReason: "You give practical, calm advice — not judgment — about pets in imperfect households",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
  ],

  "Nature & Sustainability": [
    {
      avatar: "🌍",
      name: "Claire",
      age: "24–36",
      occupation: "Marketing Executive",
      goals: ["Reduce her personal carbon footprint meaningfully", "Make sustainable swaps without sacrificing quality of life", "Support brands that are actually ethical"],
      painPoints: ["Eco-anxiety is real and she doesn't know what actually helps", "Greenwashing makes it impossible to know who to trust", "Sustainable products are often expensive and ugly"],
      contentWants: "Honest sustainability swaps with real impact data and no guilt-tripping",
      followReason: "You focus on what she CAN do rather than making her feel terrible about what she can't",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
    {
      avatar: "🏕️",
      name: "Sam",
      age: "22–35",
      occupation: "Physical Therapist",
      goals: ["Get outside more and disconnect from screens", "Learn hiking and camping without looking like a tourist", "Find wild, uncrowded natural spaces near cities"],
      painPoints: ["Doesn't know where to find off-the-beaten-path nature spots", "Gear advice is always aimed at serious adventurers", "Feels like he's always showing up underprepared for outdoor activities"],
      contentWants: "Accessible outdoor adventure content for people who want to start without spending $2k on gear",
      followReason: "You make outdoor access feel like it's for everyone — not just experienced adventurers",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
  ],

  "Art & Design": [
    {
      avatar: "🎨",
      name: "Zara",
      age: "18–28",
      occupation: "Art Student",
      goals: ["Develop a distinctive artistic style", "Turn her art into income through prints or commissions", "Build an audience that actually buys"],
      painPoints: ["Creates constantly but nothing sells", "Doesn't know how to price her work", "Social media feels fake and commercial — at odds with her art"],
      contentWants: "Business of art content: pricing, selling, licensing, and building an audience as an artist",
      followReason: "You prove that commercial success and artistic integrity aren't opposites",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "💡",
      name: "Marcus",
      age: "25–40",
      occupation: "UX Designer",
      goals: ["Level up from UX into brand or visual design", "Stay current with design trends without chasing every one", "Build a side project that showcases his design skills"],
      painPoints: ["Feels stuck at mid-level with no clear path forward", "Tool tutorials are everywhere but design thinking content is rare", "Portfolio lacks personal creative work — all client projects"],
      contentWants: "Design thinking, creative process, and career growth content for working designers",
      followReason: "You talk about design as a craft and a career — not just tools and tutorials",
      engagementScore: "Medium",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
  ],

  "Music": [
    {
      avatar: "🎸",
      name: "Carlos",
      age: "18–30",
      occupation: "Aspiring Musician",
      goals: ["Grow a real fanbase for his music", "Release music that reaches people beyond his friend group", "Figure out how to monetize without selling out"],
      painPoints: ["Streams are in double digits after months of releases", "Doesn't understand music marketing or the industry", "Feels invisible in an oversaturated market"],
      contentWants: "Music marketing, release strategy, and building a fanbase as an independent artist",
      followReason: "You understand the indie artist struggle and give real strategy — not 'just be authentic'",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "🎹",
      name: "Lily",
      age: "22–35",
      occupation: "Music Teacher",
      goals: ["Take her playing from good to genuinely expressive", "Learn music production to create her own backing tracks", "Build a YouTube/Instagram presence around music"],
      painPoints: ["Technically competent but emotionally flat in performance", "Production software like Ableton feels like learning a new language", "Doesn't know how to show her musicianship on social media"],
      contentWants: "Music theory made practical, home production guides, and creator content for musicians",
      followReason: "You bridge the gap between playing music and sharing it — two skills she hasn't connected yet",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Reels"],
    },
  ],

  "Gaming": [
    {
      avatar: "🎮",
      name: "Liam",
      age: "16–28",
      occupation: "Student",
      goals: ["Improve his gameplay in his main game", "Build a small streaming audience", "Find a community of people who take gaming as seriously as he does"],
      painPoints: ["Plateaued at the same rank for months", "Streams to 0 viewers and doesn't know how to grow", "Gaming content is often low-effort and repetitive"],
      contentWants: "High-level gameplay tips, streaming growth advice, and genuinely entertaining gaming content",
      followReason: "You're skilled AND entertaining — most gaming creators are one or the other, not both",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "👩‍💻",
      name: "Jade",
      age: "20–32",
      occupation: "Software Developer",
      goals: ["Find her gaming community as an adult woman gamer", "Get into game development as a hobby", "Discover games outside her usual genre"],
      painPoints: ["Gaming spaces are often unwelcoming to women", "Doesn't know where to find people who share her taste", "Wants to try game dev but doesn't know where to start"],
      contentWants: "Inclusive gaming community content and game development beginner content",
      followReason: "You make the gaming space feel welcoming and your taste in games actually aligns with hers",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Carousels"],
    },
  ],

  "Parenting & Family": [
    {
      avatar: "🍼",
      name: "Jessica",
      age: "25–38",
      occupation: "New Mom",
      goals: ["Survive the newborn phase without losing her mind", "Figure out sleep training that doesn't feel cruel", "Find her identity again outside of 'mom'"],
      painPoints: ["Contradictory advice from every direction leaves her more confused", "Sleep deprivation is affecting her marriage", "Feels guilty for not loving every moment of motherhood"],
      contentWants: "Honest, non-judgmental new parent content that doesn't pretend it's all beautiful",
      followReason: "You're honest that it's hard without making her feel like she's failing",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
    },
    {
      avatar: "👨‍👦",
      name: "Derek",
      age: "30–45",
      occupation: "Dad",
      goals: ["Be genuinely present with his kids, not just physically there", "Raise emotionally intelligent children", "Navigate screen time debates with confidence"],
      painPoints: ["Gets home from work and reaches for his phone instead of being present", "Doesn't have a model for emotional parenting from his own childhood", "Parenting content is almost always aimed at moms"],
      contentWants: "Real content for dads about presence, emotional intelligence, and engaged fatherhood",
      followReason: "You speak to dads as capable, important parents — not sidekicks to moms",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Mixed"],
    },
  ],

  "Sports": [
    {
      avatar: "⚽",
      name: "Marco",
      age: "16–30",
      occupation: "Amateur Athlete",
      goals: ["Level up his game enough to make a competitive team", "Train smarter with better recovery and nutrition", "Understand the mental side of sports performance"],
      painPoints: ["Trains hard but isn't improving as fast as peers", "Gets injured repeatedly and doesn't know why", "Mental performance is his biggest limiter — nobody talks about this"],
      contentWants: "Sport-specific skill breakdowns, athletic recovery content, and sports psychology",
      followReason: "You help him see the game differently — technically and mentally",
      engagementScore: "High",
      purchasePotential: "Medium",
      preferredFormats: ["Reels", "Mixed"],
    },
    {
      avatar: "🏆",
      name: "Karen",
      age: "30–50",
      occupation: "Recreational Runner",
      goals: ["Complete her first marathon", "Avoid the injuries that derailed her last training cycle", "Find community in her sport"],
      painPoints: ["Training plans feel overwhelming and she always falls behind", "Injuries make her feel like her body is working against her", "Running is lonely and she craves community"],
      contentWants: "Accessible endurance sport content: training plans, injury prevention, and running community",
      followReason: "You make marathon training feel achievable for people who are not fast — just determined",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Carousels", "Mixed"],
    },
  ],

  "DIY & Crafts": [
    {
      avatar: "🔨",
      name: "Paul",
      age: "28–50",
      occupation: "Homeowner",
      goals: ["Fix and improve his home without hiring expensive contractors", "Build his first piece of furniture from scratch", "Learn the skills his dad had that he never got to learn"],
      painPoints: ["Starts projects with no plan and abandons them halfway", "Doesn't know which tools are actually necessary for beginners", "YouTube tutorials assume he already owns a workshop"],
      contentWants: "Beginner home DIY and woodworking with real beginner mistakes acknowledged",
      followReason: "You show the failures alongside the wins — it makes him trust that he can do it too",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
    },
    {
      avatar: "🧶",
      name: "Nina",
      age: "22–40",
      occupation: "Content Creator / Crafter",
      goals: ["Sell her handmade products online", "Build an aesthetic brand around her craft", "Find her community of fellow makers"],
      painPoints: ["Etsy shop is getting no traffic or sales", "Doesn't know how to photograph her products to look professional", "Priced too low and is essentially working for free"],
      contentWants: "Business of crafts: Etsy SEO, product photography, pricing, and building a maker brand",
      followReason: "You help her turn her passion into profit without making it feel corporate or soulless",
      engagementScore: "High",
      purchasePotential: "High",
      preferredFormats: ["Reels", "Carousels"],
    },
  ],
};

// ─── Hashtags per niche (where to find this audience on Instagram) ────────────

const NICHE_HASHTAGS: Record<string, string[]> = {
  "Fitness & Wellness":           ["fitnessmotivation", "workoutathome", "healthylifestyle", "gymlife", "wellnessjourney", "fitfam", "weightlossjourney", "homeworkout"],
  "Food & Cooking":               ["foodie", "homecooking", "mealprep", "easyrecipes", "healthyeating", "cookingathome", "foodphotography", "dinnerideas"],
  "Travel":                       ["travelgram", "solotravel", "budgettravel", "wanderlust", "travelphotography", "traveltips", "adventuretravel", "digitalnomad"],
  "Fashion":                      ["ootd", "fashionstyle", "outfitoftheday", "fashioninspo", "streetstyle", "thriftfashion", "sustainablefashion", "capsulewardrobe"],
  "Beauty & Skincare":            ["skincareroutine", "skincareobsessed", "beautytips", "glowup", "cleanbeauty", "skincareaddict", "makeuptutorial", "selfcare"],
  "Tech & Gadgets":               ["techtok", "productivity", "aitools", "gadgets", "techreview", "workfromhome", "techsetup", "softwaredeveloper"],
  "Business & Entrepreneurship":  ["entrepreneur", "sidehustle", "smallbusiness", "businesstips", "passiveincome", "startuplife", "onlinebusiness", "entrepreneurmindset"],
  "Photography & Videography":    ["photography", "photographer", "filmmaking", "contentcreator", "videography", "lightroom", "photoshoot", "behindthescenes"],
  "Education & Learning":         ["studymotivation", "studytips", "selfimprovement", "learning", "studyaesthetic", "bookrecommendations", "personaldev", "onlinelearning"],
  "Lifestyle":                    ["lifestyleblogger", "morningroutine", "slowliving", "intentionalliving", "selfimprovement", "minimalism", "dailyroutine", "mentalhealth"],
  "Comedy & Entertainment":       ["funny", "comedy", "reelscomedy", "funnyvideos", "relatable", "humor", "comediansofinstagram", "entertainmentcreator"],
  "Finance & Investing":          ["personalfinance", "investing", "financialfreedom", "moneytips", "stockmarket", "wealthbuilding", "budgeting", "debtfree"],
  "Pets & Animals":               ["dogsofinstagram", "catsofinstagram", "petlovers", "dogtraining", "pethealth", "animallover", "puppylove", "petcare"],
  "Nature & Sustainability":      ["sustainability", "ecofriendly", "zerowaste", "climateaction", "nature", "outdoors", "sustainableliving", "greenliving"],
  "Art & Design":                 ["digitalart", "artistsoninstagram", "illustration", "uidesign", "graphicdesign", "artcommunity", "creativework", "designinspiration"],
  "Music":                        ["musicproducer", "indieartist", "musicianlife", "newmusic", "songwriting", "musiccommunity", "unsigned", "musicmarketing"],
  "Gaming":                       ["gamer", "gamingcommunity", "twitchstreamer", "esports", "gaming", "pcgaming", "consolegaming", "gamedev"],
  "Parenting & Family":           ["momlife", "dadlife", "parenting", "newmom", "toddlerlife", "familyfirst", "gentleparenting", "parentingtips"],
  "Sports":                       ["athlete", "sportslife", "running", "marathon", "training", "sportsperformance", "athletemindset", "sportsmotivation"],
  "DIY & Crafts":                 ["diy", "crafts", "homediy", "diydecor", "handmade", "crafting", "etsyseller", "makerlife"],
};

// ─── Location adjustment by language ─────────────────────────────────────────

const LANGUAGE_LOCATIONS: Record<string, string[]> = {
  English:    ["United States", "United Kingdom", "Canada", "Australia"],
  Hindi:      ["India (Metro Cities)", "India (Tier 2 Cities)"],
  Spanish:    ["Mexico", "Colombia", "Argentina", "Spain"],
  Portuguese: ["Brazil (São Paulo)", "Brazil (Rio de Janeiro)"],
  Arabic:     ["Saudi Arabia", "UAE", "Egypt"],
  French:     ["France", "Canada (Quebec)", "West Africa"],
  German:     ["Germany", "Austria", "Switzerland"],
  Italian:    ["Italy"],
  Japanese:   ["Japan"],
  Korean:     ["South Korea"],
  Turkish:    ["Turkey"],
  Indonesian: ["Indonesia", "Southeast Asia"],
};

// ─── Format scoring ───────────────────────────────────────────────────────────

function scoreProfile(profile: ProfileBase, format: string): number {
  if (format === "Mixed") return 3;
  return profile.preferredFormats.includes(format as ProfileBase["preferredFormats"][0]) ? 5 : 1;
}

// ─── Main export ──────────────────────────────────────────────────────────────

export function getPotentialCustomers(
  niche: string,
  format: string,
  language: string,
  count = 4
): CustomerProfile[] {
  const pool = PROFILES[niche] ?? [];

  if (pool.length === 0) return [];

  const locations = LANGUAGE_LOCATIONS[language] ?? ["Global"];

  const scored = pool.map(p => ({ profile: p, score: scoreProfile(p, format) + Math.random() * 2 }));
  scored.sort((a, b) => b.score - a.score);

  const allHashtags = NICHE_HASHTAGS[niche] ?? ["instagram", "creator", "content"];

  return scored.slice(0, count).map(({ profile: p }, i) => {
    // Each profile gets 3 different hashtags from the pool, offset by index
    const offset = i * 3;
    const hashtags = p.hashtags ?? [
      allHashtags[offset % allHashtags.length],
      allHashtags[(offset + 1) % allHashtags.length],
      allHashtags[(offset + 2) % allHashtags.length],
    ];
    return {
      avatar: p.avatar,
      name: p.name,
      age: p.age,
      occupation: p.occupation,
      location: locations[i % locations.length],
      goals: p.goals,
      painPoints: p.painPoints,
      contentWants: p.contentWants,
      followReason: p.followReason,
      engagementScore: p.engagementScore,
      purchasePotential: p.purchasePotential,
      hashtags,
    };
  });
}
